# Generated by Django 4.1.5 on 2023-01-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='replyto',
            new_name='replyto_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='replyto_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
